title: Chance Krueger
logo: /images/Professional_Headshot_Small.PNG
description: 4th Year Student at the University of Arizona • Computer Science
resume: [Link to Resume](https://github.com/Chance-Krueger/Chance-Krueger.github.io/blob/2b9053f7eb53dd961aea2fed7bfd4d6e30e571a1/images/Internship%20Resume%202025%20with%20Certifications.pdf)
#show_downloads: true
theme: jekyll-theme-minimal
